### ISSUE TITLE
Relation to cmd2/plugins/ext_test

### ISSUE THREAD

**Issue by lovetoburnswhen** [python-cmd2/cmd2-ext-test#3]
Is there a reason this is a separate package when the main `cmd2` repo has a seemingly identical `ext_test.py`? Are they kept in lock-step or should one be considered more up to date.

Thanks

**Comment by anselor** [comment]
This was recently moved into the cmd2 repo because it's a plugin that we want to actively maintain and keep in sync. The hope is it'll be easier to keep in sync if it's in the same repo and tested together. 

I think in the future we'll only spin out into a separate project if it's a plugin that is retired and will be separately maintained for a legacy version of cmd2.

**Comment by lovetoburnswhen** [comment]
I see, what is currently the recommended way of importing into your test file? 
Currently we have `cmd2-ext-test` as a separate dependency and importing it as in the documentation.

**Comment by anselor** [comment]
Sorry about the confusion. The usage is identical and the documentation is still correct. 

What we've changed is where the source code will be homed. Plugins for cmd2 will still be packaged as a separate python wheel and will be separately distributed from the main cmd2 library.

**Comment by tleonhardt** [comment]
@anselor Should we delete this old repository to avoid confusion?

**Comment by anselor** [comment]
@tleonhardt Yes, but we should do an updated release with the documentation updated to point to the new location before getting rid of this. That way pypi isn't pointing at the wrong thing.

**Comment by anselor** [comment]
@tleonhardt @Frank5000 
I've published version 0.2.0 of this plugin from the cmd2 repo with updated links that refer to its home inside of the main cmd2 repo.
